import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Image from "next/image";
// import Iphone from '@/components/Iphone'

export const metadata: Metadata = {
    title: "MODII",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <div className="iphone-container">
            {children}
        </div>

        </body>
        </html>
    );
}
