import type { Metadata } from "next";
import "./globals.css";
import React from "react";
// import Iphone from '@/components/Iphone'

export const metadata: Metadata = {
  title: "MODII",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      {/*<Iphone>*/}
      <div className="iphone-container">
        {children}
      </div>
      {/*</Iphone>*/}
      </body>
    </html>
  );
}
